language: python
python: 3.6

before_install:
  - nvm install
  - npm install
  - pip3 install coala-bears
  - export PATH=$PATH:./node_modules/.bin
  - export NODE_PATH=$NODE_PATH:./node_modules

script:
  - coala --non-interactive -V
  - npm run build
  - ./.ci/deploy.sh

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  "on":
    branch: master
    condition: -z "$ENCRYPTION_LABEL"
