language: python
python: 3.6

before_install:
  - npm i pnpm -g
  - pnpm install
  - cd node_modules/jquery.i18n
  - mkdir libs
  - cd libs
  - REPO=https://github.com/santhoshtr/CLDRPluralRuleParser.git
  - git clone --recurse-submodules $REPO
  - ls
  - cd ../../..
  - ls
  - pnpm install
  - pip3 install coala-bears
  - export PATH=$PATH:./node_modules/.bin
  - export NODE_PATH=$NODE_PATH:./node_modules

script:
  - coala --non-interactive -V
  - pnpm run build
  - ./.ci/deploy.sh

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  "on":
    branch: master
    condition: -z "$ENCRYPTION_LABEL"
